app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Guest
Route::get('/', 'GuestController@index');
Route::get('answer-survey/{id}/', 'GuestController@showSurvey');
Route::post('answer-survey/{id}/store', 'GuestController@storeAnswer');

// Survey
Route::get('survey/{id}/option/create', 'SurveyController@createOption');
Route::post('survey/{id}/option/store', 'SurveyController@storeOption');
Route::get('survey/{id}/option/{option_id}/edit', 'SurveyController@editOption');
Route::post('survey/{id}/option/{option_id}/update', 'SurveyController@updateOption');
Route::resource('survey', 'SurveyController');

// Auth
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

app/Survey.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Survey extends Model
{
    //
}

app/Http/Controllers/SurveyController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Survey;
use App\AnswerOption;

class SurveyController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $surveys = Survey::all();

        return view('survey/index')
            ->with('surveys', $surveys)
            ->with('page_title', 'Survey List');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('survey/create')
            ->with('page_title', 'Create Survey');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|unique:surveys|max:75',
            'description' => 'max:255'
        ]);

        $survey = new Survey;
        $survey->title = $request->title;
        $survey->description = $request->description;
        $survey->save();

        $request->session()->flash('success_message', 'Successfully added record.');

        return redirect()->route('survey.edit', $survey->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $survey = Survey::find($id);
        $answerOptions = AnswerOption::where('survey_id', $id)->get();

        $surveyResults = DB::table('answer_options')
             ->select('answer_option_id', 'answer_options.title', DB::raw('count(*) as total'))
             ->join('guest_answers', 'answer_options.id', '=', 'guest_answers.answer_option_id')
             ->where('answer_options.survey_id', $id)
             ->groupBy('answer_option_id')->get();

        return view('survey/edit')
            ->with('survey', $survey)
            ->with('answerOptions', $answerOptions)
            ->with('surveyResults', $surveyResults)
            ->with('page_title', 'Edit Survey');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required|max:75',
            'description' => 'max:255'
        ]);

        $survey = Survey::find($id);
        $survey->title = $request->title;
        $survey->description = $request->description;
        $survey->status = $request->status;
        $survey->save();

        $request->session()->flash('success_message', 'Successfully updated record');

        return redirect()->route('survey.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function createOption($surveyId)
    {
        $survey = Survey::find($surveyId);

        return view('survey/create_option')
            ->with('survey', $survey)
            ->with('page_title', 'Create Answer Option');
    }

    public function storeOption(Request $request, $surveyId)
    {
        $this->validate($request, [
            'title' => 'required|max:75',
        ]);

        $answerOption = new AnswerOption;
        $answerOption->survey_id = $surveyId;
        $answerOption->title = $request->title;
        $answerOption->save();

        $request->session()->flash('success_message', 'Successfully added record.');

        return redirect()->route('survey.edit', $surveyId);
    }

    public function editOption($surveyId, $answerOptionId)
    {
        $survey = Survey::find($surveyId);
        $answerOption = AnswerOption::find($answerOptionId);

        return view('survey/edit_option')
            ->with('survey', $survey)
            ->with('answerOption', $answerOption)
            ->with('page_title', 'Edit Answer Option');;
    }

    public function updateOption(Request $request, $surveyId, $answerOptionId)
    {
        $this->validate($request, [
            'title' => 'required|max:75',
        ]);

        $answerOption = AnswerOption::find($answerOptionId);
        $answerOption->title = $request->title;
        $answerOption->save();

        $request->session()->flash('success_message', 'Successfully updated answer option.');

        return redirect()->route('survey.edit', $surveyId);
    }
}

resources/views/survey/create.blade.php
@extends('admin_template')

@section('head')
@endsection

@section('breadcrumbs')
<li><a href="{{ route('survey.index') }}"><i class="fa fa-dashboard"></i> Survey List</a></li>
<li class="active">Create</li>
@endsection

@section('content')
<div class="row">
	<div class="col-xs-12">
		@include('partials.flash_message')
		<div class="box">
			<div class="box-body">
				<form action="{{ route('survey.store') }}" method="POST">

					{!! csrf_field() !!}

					<div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
						<label>Title</label>
						<input type="text" name="title" value="{{{ old('title') }}}" class="form-control" />
					</div>

					<div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
						<label>Description</label>
						<textarea name="description" class="form-control" placeholder="Place some text here" ></textarea>
					</div>

					<button type="submit" class="btn btn-primary">Create Survey</button>
					<a href="{{ route('survey.index') }}" class="btn"><u>Cancel</u></a>

				</form>	    
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->
@endsection

@section('script')
@endsection

resources/views/survey/create_option.blade.php
@extends('admin_template')

@section('head')
@endsection

@section('breadcrumbs')
	<li><a href="{{ route('survey.index') }}">Survey List</a></li>
	<li><a href="{{ route('survey.edit', $survey->id) }}">{{ $survey->title }}</a></li>
	<li class="active">Create Answer Option</li>
@endsection

@section('content')

<div class="row">
	<div class="col-xs-12">
		@include('partials.flash_message')
		<h4>Survey: {{ $survey->title }}</h4>
		
		<div class="box">
			<div class="box-body">
				
				<form action="/survey/{{$survey->id}}/option/store" method="POST">
		        	{!! csrf_field() !!}
		            
		            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
	                  <label>Title</label>
	                  <input type="text" name="title" value="{{{ old('title') }}}" class="form-control" />
	                </div>

		            <button type="submit" class="btn btn-primary">Create Answer Option</button>
		            <a href="{{ route('survey.edit', $survey->id) }}" class="btn"><u>Cancel</u></a>
		        </form>	    

			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->

@endsection

@section('script')
@endsection

resources/views/survey/edit.blade.php
@extends('admin_template')

@section('head')
@endsection

@section('breadcrumbs')
	<li><a href="{{ route('survey.index') }}">Survey List</a></li>
	<li class="active">Edit</li>
@endsection

@section('content')

<div class="row">
	<div class="col-xs-12">
		@include('partials.flash_message')
		<h4>{{ $survey->title }}</h4>

		<!-- Custom Tabs -->
		<div class="nav-tabs-custom">
			<ul class="nav nav-tabs">
				<li class="active"><a href="#tab_1" data-toggle="tab">Survey Details</a></li>
				<li><a href="#tab_2" data-toggle="tab">Answer Options</a></li>
				<li><a href="#tab_3" data-toggle="tab">Survey Results</a></li>
			</ul>

			<div class="tab-content">
				<div class="tab-pane active" id="tab_1">
					<div class="box">
						<div class="box-body">
							<form action="{{ route('survey.update', $survey->id) }}" method="POST">

								{!! csrf_field() !!}
								<input type="hidden" name="_method" value="PUT" />
		            
					            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
				                  <label>Title</label>
				                  <input type="text" name="title" value="{{{ $survey->title or old('title') }}}" class="form-control" />
				                </div>

				                <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
					            	<label>Description</label>
					                <textarea name="description" class="form-control" placeholder="Place some text here">{{ $survey->description }}</textarea>
					            </div>

				                <div class="form-group {{ $errors->has('status') ? 'has-error' : '' }}">
				                  <label>Status</label>
				                  <select name="status" class="form-control">
				                  	<option value="1" {{ $survey->status == 1 ? 'selected="selected"' : '' }}>Published</option>
				                  	<option value="0" {{ $survey->status == 0 ? 'selected="selected"' : '' }}>Deactivated</option>
				                  </select>
				                </div>

								<button class="btn btn-primary" type="submit">Update</button>
								<a href="{{ route('survey.index') }}" class="btn"><u>Cancel</u></a>

							</form>
						</div><!-- /.box-body -->
					</div><!-- /.box -->
				</div><!-- /.tab-pane -->

				<div class="tab-pane" id="tab_2">
					@include('survey/option_index')
				</div><!-- /.tab-pane -->

				<div class="tab-pane" id="tab_3">
					@include('survey/survey_result')
				</div><!-- /.tab-pane -->

			</div><!-- /.tab-content -->
		</div><!-- nav-tabs-custom -->
	</div><!-- /.col -->
</div><!-- /.row -->
@endsection

@section('script')
    <!-- DATA TABLES SCRIPT -->
	<script src="{{ asset('admin-lte/plugins/datatables/jquery.dataTables.js') }}" type="text/javascript"></script>
	<script src="{{ asset('admin-lte/plugins/datatables/dataTables.bootstrap.js') }}" type="text/javascript"></script>

    <script type="text/javascript">
      	$('#data_table tfoot th').each( function () {
	        var title = $('#data_table thead th').eq( $(this).index() ).text();
	        $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
	    } );

		$(function () {
			var table = $('#data_table').DataTable({
				"paging": true,
				"lengthChange": true,
				"searching": true,
				"ordering": true,
				"info": true,
				"autoWidth": true
			});

		    table.columns().every( function () {
		        var that = this;
		 
		        $( 'input', this.footer() ).on( 'keyup change', function () {
		            that
		                .search( this.value )
		                .draw();
		        } );
		    } );
		});	
    </script>
@endsection

resources/views/survey/edit_option.blade.php
@extends('admin_template')

@section('head')
@endsection

@section('breadcrumbs')
	<li><a href="{{ route('survey.index') }}">Survey List</a></li>
	<li><a href="{{ route('survey.edit', $survey->id) }}">{{ $survey->title }}</a></li>
	<li class="active">Edit Answer Option</li>
@endsection

@section('content')

<div class="row">
	<div class="col-xs-12">
		@include('partials.flash_message')
		<h4>Survey: {{ $survey->title }}</h4>
		
		<div class="box">
			<div class="box-body">
				
				<form action="/survey/{{$survey->id}}/option/{{$answerOption->id}}/update" method="POST">
		        	{!! csrf_field() !!}
		            
		            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
	                  <label>Title</label>
	                  <input type="text" name="title" value="{{{ old('title', $answerOption->title) }}}" class="form-control" />
	                </div>

		            <button type="submit" class="btn btn-primary">Update</button>
		            <a href="{{ route('survey.edit', $survey->id) }}" class="btn"><u>Cancel</u></a>
		        </form>	    

			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->

@endsection

@section('script')
@endsection

resources/views/survey/index.blade.php
@extends('admin_template')

@section('content')
    <div class="row">
	    <div class="col-xs-12">
	    	<a href="{{ route('survey.create') }}" class="btn btn-primary btn-flat fa fa-plus"> Add New</a>
	    	<br/><br/>

	    @include('partials.flash_message')

	      <div class="box">
	        <div class="box-body">
	          <table id="data_table" class="table table-bordered table-striped">
	            <thead>
	              <tr>
	                <th>Title</th>
	                <th>Description</th>
	                <th>Status</th>
	              </tr>
	            </thead>
	            <tbody>
	            	@foreach($surveys as $survey)
		              <tr>
		                <td><a href="{{ route('survey.edit', $survey->id) }}">{{ $survey->title }}</td>
		                <td>{{ $survey->description }}</td>
		                <td>
	      					@if($survey->status == 0)
	      						<div class="label label-default">Deactivated</div>
	      					@elseif($survey->status == 1)
	      						<div class="label label-success">Active</div>
	      					@endif
	      				</td>
		              </tr>
		            @endforeach
	            </tbody>
	            <tfoot>
	              <tr>
	                <th>Title</th>
	                <th>Description</th>
	                <th>Status</th>
	              </tr>
	            </tfoot>
	          </table>
	        </div><!-- /.box-body -->
	      </div><!-- /.box -->
	    </div><!-- /.col -->
    </div><!-- /.row -->
@endsection


@section('script')
	<!-- DATA TABES SCRIPT -->
	<script src="{{ asset("admin-lte/plugins/datatables/jquery.dataTables.js") }}" type="text/javascript"></script>
	<script src="{{ asset("admin-lte/plugins/datatables/dataTables.bootstrap.js") }}" type="text/javascript"></script>

	<script type="text/javascript">
	  	// Setup - add a text input to each footer cell
	    $('#data_table tfoot th').each( function () {
	        var title = $('#data_table thead th').eq( $(this).index() ).text();
	        $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
	    } );

		$(function () {
			var table = $('#data_table').DataTable({
				"paging": true,
				"lengthChange": true,
				"searching": true,
				"ordering": true,
				"info": true,
				"autoWidth": true
			});

		    table.columns().every( function () {
		        var that = this;
		 
		        $( 'input', this.footer() ).on( 'keyup change', function () {
		            that
		                .search( this.value )
		                .draw();
		        } );
		    } );

		});	
	</script>
@endsection

resources/views/survey/option_index.blade.php
<a href="/survey/{{ $survey->id }}/option/create" class="btn btn-primary btn-flat fa fa-plus"> Add Answer Option</a>
<br/><br/>
<table id="data_table" class="table table-bordered table-striped">
	<thead>
	  <tr>
	    <th>Title</th>
	    <th>Status</th>
	  </tr>
	</thead>
	<tbody>
	@foreach($answerOptions as $option)
	  <tr>
	    <td><a href="/survey/{{ $survey->id }}/option/{{ $option->id }}/edit">{{ $option->title }}</td>
	    <td>
			@if($option->status == 0)
				<div class="label label-default">Deactivated</div>
			@elseif($option->status == 1)
				<div class="label label-success">Active</div>
			@endif
		</td>
	  </tr>
	 @endforeach
	</tbody>
	<tfoot>
	  <tr>
	    <th>Title</th>
	    <th>Status</th>
	  </tr>
	</tfoot>
</table>

resources/views/survey/survey_result.blade.php
<table id="data_table2" class="table table-bordered table-striped">
	<thead>
	  <tr>
	    <th>Answer</th>
	    <th>Votes</th>
	  </tr>
	</thead>
	<tbody>
	@foreach($surveyResults as $surveyResult)
	  <tr>
	    <td>{{ $surveyResult->title }}</td>
	    <td>{{ $surveyResult->total }}</td>
	  </tr>
	 @endforeach
	</tbody>
</table>